--화면7
--OrderID(history일련번호) 입력
--(담당자4명) 소속, 이름, 상태, 시작시간, 어플리케이션코드, 결과, 오류조치방안 등 다양한 정보 출력 // 페이징 없음
WITH NAMEFILTER_T AS (
    SELECT EZ_JOB_MAPPER.JOB_NAME, DEPT_NM, USER_NM, USER_HP
    FROM EZ_JOB_MAPPER,
         (
             SELECT EZ_USER.USER_CD, EZ_USER.USER_NM, EZ_DEPT.DEPT_NM, EZ_USER.USER_HP
             FROM EZ_USER, EZ_DEPT
             WHERE EZ_USER.DEPT_CD = EZ_DEPT.DEPT_CD(+)
             )
    WHERE EZ_JOB_MAPPER.USER_CD_1 = USER_CD(+)
),
NAMEFILTER_2T AS (
    SELECT EZ_JOB_MAPPER.JOB_NAME, DEPT_NM, USER_NM, USER_HP
    FROM EZ_JOB_MAPPER,
         (
             SELECT EZ_USER.USER_CD, EZ_USER.USER_NM, EZ_DEPT.DEPT_NM, EZ_USER.USER_HP
             FROM EZ_USER, EZ_DEPT
             WHERE EZ_USER.DEPT_CD = EZ_DEPT.DEPT_CD(+)
             )
    WHERE EZ_JOB_MAPPER.USER_CD_2 = USER_CD(+)
),
NAMEFILTER_3T AS (
    SELECT EZ_JOB_MAPPER.JOB_NAME, DEPT_NM, USER_NM, USER_HP
    FROM EZ_JOB_MAPPER,
         (
             SELECT EZ_USER.USER_CD, EZ_USER.USER_NM, EZ_DEPT.DEPT_NM, EZ_USER.USER_HP
             FROM EZ_USER, EZ_DEPT
             WHERE EZ_USER.DEPT_CD = EZ_DEPT.DEPT_CD(+)
             )
    WHERE EZ_JOB_MAPPER.USER_CD_3 = USER_CD(+)
),
NAMEFILTER_4T AS (
    SELECT EZ_JOB_MAPPER.JOB_NAME, DEPT_NM, USER_NM, USER_HP
    FROM EZ_JOB_MAPPER,
         (
             SELECT EZ_USER.USER_CD, EZ_USER.USER_NM, EZ_DEPT.DEPT_NM, EZ_USER.USER_HP
             FROM EZ_USER, EZ_DEPT
             WHERE EZ_USER.DEPT_CD = EZ_DEPT.DEPT_CD(+)
             )
    WHERE EZ_JOB_MAPPER.USER_CD_4 = USER_CD(+)
),
ERROR_ORDER_T AS (
    SELECT EZ_HISTORY.ORDER_TIME, EZ_HISTORY.APPLICATION, EZ_HISTORY.GROUP_NAME, EZ_HISTORY.DESCRIPTION, EZ_HISTORY.ORDER_ID,
           EZ_JOB_MAPPER.ERROR_DESCRIPTION, EZ_HISTORY.JOB_NAME, EZ_HISTORY.STATUS
    FROM EZ_HISTORY,
         EZ_JOB_MAPPER
    WHERE EZ_HISTORY.JOB_NAME = EZ_JOB_MAPPER.JOB_NAME(+)
      --AND EZ_HISTORY.ORDER_ID = '2b79f' -- 작업일련번호 입력
),
DEFJOB_T AS (
    SELECT EZ_HISTORY.JOB_NAME, DEF_JOB.NODE_ID, DEF_JOB.CMD_LINE, EZ_HISTORY.ORDER_ID
    FROM EZ_HISTORY,
         DEF_JOB
    WHERE EZ_HISTORY.JOB_NAME = DEF_JOB.JOB_NAME(+)
      --AND EZ_HISTORY.ORDER_ID = '2b79f' -- 작업일련번호 입력
)

SELECT ERROR_ORDER_T.JOB_NAME,
       NAMEFILTER_T.DEPT_NM AS 담당자1부서, NAMEFILTER_T.USER_NM AS 담당자1이름, NAMEFILTER_T.USER_HP AS 담당자1전화,
       NAMEFILTER_2T.DEPT_NM AS 담당자2부서, NAMEFILTER_2T.USER_NM AS 담당자2이름, NAMEFILTER_2T.USER_HP AS 담당자2전화,
       NAMEFILTER_3T.DEPT_NM AS 담당자3부서, NAMEFILTER_3T.USER_NM AS 담당자3이름, NAMEFILTER_3T.USER_HP AS 담당자3전화,
       NAMEFILTER_4T.DEPT_NM AS 담당자4부서, NAMEFILTER_3T.USER_NM AS 담당자4이름, NAMEFILTER_3T.USER_HP AS 담당자4전화,
       ORDER_TIME, APPLICATION, GROUP_NAME, DESCRIPTION, NODE_ID, CMD_LINE, STATUS, ERROR_DESCRIPTION
FROM NAMEFILTER_T, NAMEFILTER_2T, NAMEFILTER_3T, NAMEFILTER_4T, ERROR_ORDER_T, DEFJOB_T
WHERE ERROR_ORDER_T.JOB_NAME = NAMEFILTER_T.JOB_NAME
  AND ERROR_ORDER_T.JOB_NAME = NAMEFILTER_2T.JOB_NAME
  AND ERROR_ORDER_T.JOB_NAME = NAMEFILTER_3T.JOB_NAME
  AND ERROR_ORDER_T.JOB_NAME = NAMEFILTER_4T.JOB_NAME
  AND ERROR_ORDER_T.ORDER_ID = '2avq3' -- 작업일련번호 입력
  AND DEFJOB_T.ORDER_ID = '2avq3'-- 작업일련번호 입력


