----------------------------전체작업 조회-------------------------
/*ODATE : 오늘날짜(200812로 가정)
OPERATION_STATUS : 기간계 상태(STATUS/FAIL)
CNT_OPERATION : 기간계 CNT
INFORMATION_STATUS : 정보계 상태
CNT_INFORMATION : 정보계 CNT
EDW_STATUS : EDW 상태(STATUS/FAIL)
CNT_EDW : EDW CNT
ETC_STATUS : 그 외 상태
CTN_ETC : 그 외 CNT*/
-------------------------Null값 가공--------------------------
WITH OPERATION AS (
    SELECT ODATE, STATUS, count(*) CNT_OPERATION
    FROM EZ_HISTORY
    WHERE APPLICATION LIKE '01%'
    GROUP BY STATUS, ODATE
), INFORMATION AS (
    SELECT ODATE, STATUS, count(*) CNT_INFORMATION
    FROM EZ_HISTORY
    WHERE APPLICATION LIKE '02%'
    GROUP BY STATUS, ODATE
), EDW AS (
    SELECT ODATE, STATUS, count(*) CNT_EDW
    FROM EZ_HISTORY
    WHERE APPLICATION LIKE '03%'
    GROUP BY STATUS, ODATE
), ETC AS (
    SELECT ODATE, STATUS, count(*) CNT_ETC
    FROM EZ_HISTORY
    WHERE REGEXP_LIKE(APPLICATION, '99|10|11|BMC|16|15|12')
    GROUP BY STATUS, ODATE
)
SELECT OPERATION.ODATE ODATE, OPERATION.STATUS OPERATION_STATUS, CNT_OPERATION, DECODE(INFORMATION.STATUS, NULL, 'FAIL', INFORMATION.STATUS) INFORMATION_STATUS, DECODE(CNT_INFORMATION, NULL, 0, CNT_INFORMATION) CNT_INFORMATION,
DECODE (EDW.STATUS, NULL, 'FAIL', EDW.STATUS) AS EDW_STATUS, DECODE(CNT_EDW, NULL, 0, CNT_EDW) AS CNT_EDW, DECODE(ETC.STATUS, NULL, 'FAIL', ETC.STATUS) ETC_STATUS, DECODE(CNT_ETC, NULL, 0, CNT_ETC) CNT_ETC
--NULL값 처리
FROM OPERATION, INFORMATION, EDW, ETC
WHERE OPERATION.STATUS = INFORMATION.STATUS(+) AND OPERATION.STATUS = EDW.STATUS(+) AND OPERATION.STATUS = ETC.STATUS(+) AND
OPERATION.ODATE = INFORMATION.ODATE(+) AND OPERATION.ODATE = EDW.ODATE(+) AND OPERATION.ODATE = ETC.ODATE(+) AND OPERATION.ODATE = '200812'--OPERATION.ODATE= 200812 /200813 (날짜로 필터) 오늘날짜는 200812일이라고 가정함
ORDER BY OPERATION.ODATE, OPERATION.STATUS;


-----------------------------------NULL값 처리 전-----------------------------
WITH OPERATION AS (
    SELECT ODATE, STATUS, count(*) CNT_OPERATION
    FROM EZ_HISTORY
    WHERE APPLICATION LIKE '01%'
    GROUP BY STATUS, ODATE
), INFORMATION AS (
    SELECT ODATE, STATUS, count(*) CNT_INFORMATION
    FROM EZ_HISTORY
    WHERE APPLICATION LIKE '02%'
    GROUP BY STATUS, ODATE
), EDW AS (
    SELECT ODATE, STATUS, count(*) CNT_EDW
    FROM EZ_HISTORY
    WHERE APPLICATION LIKE '03%'
    GROUP BY STATUS, ODATE
), ETC AS (
    SELECT ODATE, STATUS, count(*) CNT_ETC
    FROM EZ_HISTORY
    WHERE REGEXP_LIKE(APPLICATION, '99|10|11|BMC|16|15|12')
    GROUP BY STATUS, ODATE
)
SELECT *
FROM OPERATION, INFORMATION, EDW, ETC
WHERE OPERATION.STATUS = INFORMATION.STATUS(+) AND OPERATION.STATUS = EDW.STATUS(+) AND OPERATION.STATUS = ETC.STATUS(+) AND
OPERATION.ODATE = INFORMATION.ODATE(+) AND OPERATION.ODATE = EDW.ODATE(+) AND OPERATION.ODATE = ETC.ODATE(+)-- OPERATION.ODATE= 200812 /200813 (날짜로 필터)
ORDER BY OPERATION.ODATE, OPERATION.STATUS;

SELECT count(*)
FROM EZ_HISTORY;



-- STAUTS를 Fail로 Setting
UPDATE EZ_HISTORY SET
STATUS ='FAIL'
WHERE ORDER_ID IN (SELECT ALARM.ORDER_ID
FROM EZ_HISTORY, ALARM
WHERE EZ_HISTORY.ORDER_ID = ALARM.ORDER_ID);


--Fail 들어간 Data 확인
SELECT APPLICATION, ORDER_ID
FROM EZ_HISTORY
WHERE STATUS = 'FAIL';

